# email to which errors will be sent
email: "dsg2157@columbia.edu"

# Location of the config file for barcodeIdentification
bID: "config_6_rounds_mTOR.txt"

# Location of the samples json file produced with the fastq2json.py script 
samples: "./samples.json"

# Output directory  
output_dir: ""

# Temporary directory
temp_dir: "/burg/mjlab/projects/spidr_preprocessing_dg/scratch"

# Currently "mm10" and "hg38" available
assembly: "hg38"

# Number of barcodes used
num_tags: "7"

# Number of chunks to split fastq
num_chunks: 10

# Format for splitting clusters
rounds_format: 'format_6_rounds_mTOR.txt'

# File for cutadapt
cutadapt_oligos: "oligo2_reverse.fasta"

# Bowtie2 Indexes
# Note: mm10 index currently not available at specified filepath
bowtie2_index:
    hg38: "/burg/mjlab/projects/spidr_preprocessing_dg/ncRNA_bt2/ncRNA"
    mm10: "/burg/mjlab/projects/spidr_preprocessing_dg/mm10_ncRNA_bt2/mm10_ncRNA"

# Star Indexes
# Note: mm10 index currently not available at specified filepath
star_index:
    mm10: "/burg/mjlab/projects/spidr_preprocessing_dg/mus_musculus/GRCm38/star"
    hg38: "/burg/mjlab/projects/spidr_preprocessing_dg/hg38"
